version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 140502
      MYSQL_DATABASE: ufanet_tasks
      TZ: Asia/Yekaterinburg
    volumes:
      - ./db/data:/var/lib/mysql