{
 "title": "Task system metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metricCategory",
    "label": "metric-category",
    "query": {
     "query": "label_values(org_example_MonitoringJmxMBean_Value,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WorkerAverageTimeWaitingBy${metricCategory}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "metricCategory",
   "targets": [
    {
     "expr": "org_example_MonitoringJmxMBean_Value{name=~\"WorkerAverageTimeWaitingBy${metricCategory}.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TaskAverageTimeExecutionBy${metricCategory}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "repeat": "metricCategory",
   "targets": [
    {
     "expr": "org_example_MonitoringJmxMBean_Value{name=~\"TaskAverageTimeExecutionBy${metricCategory}.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TakenTaskCountBy${metricCategory}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "repeat": "metricCategory",
   "targets": [
    {
     "expr": "org_example_MonitoringJmxMBean_Value{name=~\"TakenTaskCountBy${metricCategory}.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CompletedTaskCountBy${metricCategory}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "repeat": "metricCategory",
   "targets": [
    {
     "expr": "org_example_MonitoringJmxMBean_Value{name=~\"CompletedTaskCountBy${metricCategory}.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}