DROP TABLE tasks;
CREATE TABLE tasks (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(50) NOT NULL,
    canonical_name VARCHAR(255) NOT NULL,
    params JSON NOT NULL,
    status ENUM('PENDING','READY','PROCESSING','FAILED','COMPLETED','CANCELED','NONE') NOT NULL,
    execution_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    retry_count INT DEFAULT 0
);
